<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>viewBtn</name>
   <tag></tag>
   <elementGuidId>8a433a92-5090-4258-be86-f3f826eba33d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'btnView']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='btnView']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnView</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69133de9-a64a-4739-8c7d-bf5e49bf4da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61a55215-2dfc-4b1d-b878-dcf21f888f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>69f6b155-853b-4400-88e4-0af1fab8d679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnView</value>
      <webElementGuid>7d7d0ec2-5de1-451e-ae1a-02aa7e34ac09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>355c7f37-2f56-476e-a55c-2d62d2a25b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnView&quot;)</value>
      <webElementGuid>303554f0-2d5d-47c4-9161-ea3b8098b1ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnView']</value>
      <webElementGuid>9775163b-d892-422b-b6ea-992c86763527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='employeeSelectForm']/fieldset/p/input</value>
      <webElementGuid>b8c7852f-adcf-4674-8799-d096be540b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>b64dce3e-37e3-454c-91ba-84723fa9983c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnView']</value>
      <webElementGuid>25fb4b98-a58d-4d6a-948d-162d71e39ec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
